name: Test on Debian

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script in container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace ubuntu:latest /bin/bash -c "
            sed -i 's/sudo //g' /workspace/packages_update.sh && \
            chmod +x /workspace/packages_update.sh && \
            /workspace/packages_update.sh
          "